using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Media;
//using MonoGame_Textbox;
//using MonoGame_Test;
using Microsoft.Xna.Framework.Content;

namespace Arkanoid.Classes
{
    class NameEnter
    {

        public NameEnter()
        {

        }
        public void LoadContent(ContentManager Content)
        {

        }
    }
}
